spring:
  main:
    allow-bean-definition-overriding: true

app:
  bigquery:
    project-id: da-net-uap-dv-8ef
    dataset: SINCERA_NPAM_DS
    table: npam_events
    lookup-table: da-net-uap-dv-8ef.SINCERA_NPAM_DS.npam_metric_type_lookup
    dlq-bucket: my-npam-dlq-bucket   # <--- set your GCS DLQ bucket

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:pkc-xxxxx.confluent.cloud:9092}
  topic: ${KAFKA_TOPIC:PROD_MAESTROE_ASSURANCE_PM_PERIODIC_DATA}
  group-id: ${KAFKA_GROUP_ID:npam-consumer-group}
  username: ${KAFKA_USERNAME:}     # set via environment / secret
  password: ${KAFKA_PASSWORD:}     # set via environment / secret
  concurrency: ${KAFKA_CONCURRENCY:5}        # concurrent consumers per JVM
  max-poll-records: ${KAFKA_MAX_POLL_RECORDS:1000}
  batch:
    size: ${BATCH_SIZE:200}        # number of rows to send to BigQuery per insertAll
    poll-timeout-ms: ${POLL_TIMEOUT_MS:1000} # time to wait to form a batch
  auto-offset-reset: latest